//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupActivity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public System.Guid StudentID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public Nullable<int> SectionID { get; set; }
    
        public virtual Section Section { get; set; }
    }
}
